CREATE DATABASE BITACORA_PAGOS;
USE BITACORA_PAGOS;


CREATE TABLE USUARIO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(180) NOT NULL UNIQUE,
    NOMBRES VARCHAR(90) NOT NULL,
    APELLIDOS VARCHAR(90) NOT NULL,
    TELEFONO VARCHAR(90) NOT NULL UNIQUE,
    IMAGEN VARCHAR(255) NULL,
    PASSWORD_USER VARCHAR(90) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL
);

CREATE TABLE ROLES(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(90) NOT NULL UNIQUE,
    IMAGEN VARCHAR(255),
    ROUTE VARCHAR(180),
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL
);

CREATE TABLE USER_HAS_ROLES(
	ID_USER BIGINT NOT NULL,
    ID_ROL BIGINT NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL,
    FOREIGN KEY(ID_USER) REFERENCES USUARIO(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY(ID_USER, ID_ROL)
);

CREATE TABLE TIPO_CONCEPTO(
	ID_TIPO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_TIPO VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE CONCEPTO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CONCEPTO	VARCHAR(100) NOT NULL UNIQUE,
    MES  TINYINT NOT NULL,
    ANIO YEAR NOT NULL,
    ID_TIPO INT NOT NULL,
    MONTO DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_CONCEPTO(ID_TIPO)
);

/*
CREATE TABLE AFILIACION(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO BIGINT NOT NULL,
    CONDICION_LABORAL TINYINT NOT NULL,
    FECHA_AFILIACION DATETIME NOT NULL,
    FECHA_CESE DATETIME NOT NULL,
    ESTADO BOOLEAN NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
*/
CREATE TABLE MEDIO_PAGO (
    ID_MEDIO_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_MEDIO_PAGO VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE APORTE(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO BIGINT NOT NULL,
    ID_CONCEPTO BIGINT NOT NULL,
    MONTO DECIMAL(10, 2) NOT NULL,
    ID_MEDIO_PAGO INT NOT NULL,
    IMAGEN VARCHAR(255) NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY(ID_CONCEPTO) REFERENCES CONCEPTO(ID),
	FOREIGN KEY(ID_MEDIO_PAGO) REFERENCES MEDIO_PAGO(ID_MEDIO_PAGO)
);
 
CREATE TABLE SALIDA(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MOTIVO TEXT NOT NULL,
    MONTO DECIMAL(10, 2) NOT NULL,
    ID_USUARIO BIGINT NOT NULL,
    IMAGEN VARCHAR(255) NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);