CREATE DATABASE BITACORA_PAGOS;
USE BITACORA_PAGOS;


CREATE TABLE USUARIO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(180) NOT NULL UNIQUE,
    NOMBRES VARCHAR(90) NOT NULL,
    APELLIDOS VARCHAR(90) NOT NULL,
    TELEFONO VARCHAR(90) NOT NULL UNIQUE,
    IMAGEN VARCHAR(255) NULL,
    PASSWORD_USER VARCHAR(90) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL
);

CREATE TABLE ROLES(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(90) NOT NULL UNIQUE,
    IMAGEN VARCHAR(255),
    ROUTE VARCHAR(180),
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL
);

CREATE TABLE USER_HAS_ROLES(
	ID_USER BIGINT NOT NULL,
    ID_ROL BIGINT NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL,
    FOREIGN KEY(ID_USER) REFERENCES USUARIO(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY(ID_USER, ID_ROL)
);
